### ISSUE TITLE
[REQUEST Membership]: New membership for zzguang

### ISSUE THREAD

**Issue by zzguang** [openyurtio/community#11]
## GitHub Username

zzguang
## Organization you are requesting membership in

openyurtio

## Sponsors

Intel
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:

- Issues :
https://github.com/openyurtio/openyurt/issues/330

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
@zzguang Thank you for requesting member of OpenYurt.
Would you please make a pull request to [cncf/gitdm](https://github.com/cncf/gitdm#addingupdating-affiliation) to add your affiliation at first.

**Comment by zzguang** [comment]
> @zzguang Thank you for requesting member of OpenYurt.
> Would you please make a pull request to [cncf/gitdm](https://github.com/cncf/gitdm#addingupdating-affiliation) to add your affiliation at first.

Done, thanks!

**Comment by rambohe-ch** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@zzguang Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
