### ISSUE TITLE
[REQUEST Membership]: New membership for yingjianjian

### ISSUE THREAD

**Issue by yingjianjian** [openyurtio/community#12]
## GitHub Username
yingjianjian

## Organization you are requesting membership in

openyurtio

## Sponsors
Xinhua Zhiyun Technology Co., Ltd.

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/issues/263
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by felix0080** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

@yingjianjian Could you introduce yourself to the community ？

**Comment by rambohe-ch** [comment]
@yingjianjian I think you need to modify the sponsors info, and you can add your company info in sponsors items.

**Comment by rambohe-ch** [comment]
@yingjianjian Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by yingjianjian** [comment]
I am an operation and maintenance development engineer, keen on cloud native, currently engaged in kubernetes cloud native development
