### ISSUE TITLE
[REQUEST Membership]: New membership for neo502721

### ISSUE THREAD

**Issue by neo502721** [openyurtio/community#13]
## GitHub Username
neo502721

## Organization you are requesting membership in

openyurtio

## Sponsors
China Mobile 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/208
https://github.com/openyurtio/openyurt/pull/204

- Issues :
https://github.com/openyurtio/openyurt/issues/207
[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by felix0080** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

@neo502721 Could you introduce yourself to the community？

**Comment by rambohe-ch** [comment]
@neo502721 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by neo502721** [comment]
> agree +1
> 
> @neo502721 Could you introduce yourself to the community？

Hi，I work in China Mobile Shanghai Industrial Research Institute for back-end development now.  I participate in open source projects related to cloud native in spare time.  I am very gald to be member of Openyurt.

**Comment by neo502721** [comment]
> @neo502721 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

Thank you very much. It's my first organization in github. I will check the issue later.
