### ISSUE TITLE
[REQUEST Membership]: New membership for luckymrwang

### ISSUE THREAD

**Issue by luckymrwang** [openyurtio/community#15]
## GitHub Username

luckymrwang

## Organization you are requesting membership in

openyurtio

## Sponsors

Inspur

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
[openyurtio/openyurt#343](https://github.com/openyurtio/openyurt/issues/343)

- Issues :
[openyurtio/openyurt#349](https://github.com/openyurtio/openyurt/pull/349)

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by neo502721** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@luckymrwang Would you like to introduce yourself to the community ？

**Comment by luckymrwang** [comment]
> @luckymrwang Would you like to introduce yourself to the community ？

Hi，I work in Inspur for back-end development now. I participate in open source projects related to cloud native because of my company's product which is based Kubernetes and Istio. I am very gald to be member of Openyurt.

**Comment by rambohe-ch** [comment]
@luckymrwang Thank you for your response. Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by mauricewei** [comment]
My name is Wei Meng. I work in China Unicom. I'm engaged in k8s and openstack development. I'm good at Python golang programming. I'm very interested in the open source community and very happy to join openyurt community!

Two points in this issue #14 is done.
