### ISSUE TITLE
[REQUEST Membership]: New membership for cuirunxing-hub

### ISSUE THREAD

**Issue by cuirunxing-hub** [openyurtio/community#16]
## GitHub Username
cuirunxing-hub

## Organization you are requesting membership in
openyurtio

## Sponsors
inspur

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
openyurtio/openyurt#354

- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by neo502721** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@cuirunxing-hub Would you like to introduce yourself to the community ？

**Comment by cuirunxing-hub** [comment]
I have 2+ years cloud native && go experence. Focusing on network&service mesh.  Familiar with k8s code artichture inclouding informer,client-go,controller-manager,cni,operator and so on. This time,It's a good beginning to become a member of openyurt. thanks for the team of openyurt. God bless u.

**Comment by rambohe-ch** [comment]
@cuirunxing-hub Thank you for introduction.
Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
