### ISSUE TITLE
[REQUEST Membership]: New membership for gnunu

### ISSUE THREAD

**Issue by gnunu** [openyurtio/community#18]
## GitHub Username
gnunu

## Organization you are requesting membership in
openyurtio

## Sponsors
Intel

## Requirements

- [y] I have joined in the community [Dingding] and [WeChat]
- [y] I often attend Openyurt Community Week
- [y] I have reviewed the [community membership docs]
- [y] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [y] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [y] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:

- Issues :
https://github.com/openyurtio/openyurt/issues/328

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@gnunu Would you like to introduce yourself to the community ？

**Comment by gnunu** [comment]
> @gnunu Would you like to introduce yourself to the community ？

Sure. I am Chen, Shaoqiang from Intel, a software engineer woking on cloud edge software solutions such as video analytics based on heterogenous devices, and co-enginerring with customers for necessary customization or optimization. Excited to be a user and maybe(hope :)) a contributor to OpenYurt commnunity!

**Comment by rambohe-ch** [comment]
@gnunu Thank you for introduction.
Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by gnunu** [comment]
@rambohe-ch Thanks! I checked but couldn't see the message. :( Could you pls send again？
