### ISSUE TITLE
[REQUEST Membership]: New membership for liangyuanpeng

### ISSUE THREAD

**Issue by liangyuanpeng** [openyurtio/community#19]
## GitHub Username
liangyuanpeng

## Organization you are requesting membership in
openyurtio

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:  

https://github.com/openyurtio/openyurt/pull/210

- Issues :  

https://github.com/openyurtio/openyurt/issues/203

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

---

I have not idea for `devstats` and what's mean?

## About me

I am passionate about the exploration of cloud native technology and OpenYurt is one of that . I have written some OpenYurt content on zhihu.com and I will keep writing.

**Comment by rambohe-ch** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@liangyuanpeng [cncf/gitdm](https://github.com/cncf/gitdm) is used for calculating contributions based on developers and their companies by cncf. you can make up an issue to update your affiliation to [cncf/gitdm](https://github.com/cncf/gitdm).

**Comment by liangyuanpeng** [comment]
> @liangyuanpeng [cncf/gitdm](https://github.com/cncf/gitdm) is used for calculating contributions based on developers and their companies by cncf. you can make up an issue to update your affiliation to [cncf/gitdm](https://github.com/cncf/gitdm).

Thanks for your reply and what can i do for REQUEST Membership now?

**Comment by felix0080** [comment]
agree +1

**Comment by gnunu** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@liangyuanpeng Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by kadisi** [comment]
agree +1

**Comment by liangyuanpeng** [comment]
Thanks for your work!
