### ISSUE TITLE
[REQUEST Membership]: New membership for MIBc

### ISSUE THREAD

**Issue by MIBc** [openyurtio/community#20]
## GitHub Username
MIBc

## Organization you are requesting membership in
openyurtio

## Sponsors
rambohe-ch

## Requirements

- [ y ] I have joined in the community [Dingding] and [WeChat]
- [ y ] I often attend Openyurt Community Week
- [ y ] I have reviewed the [community membership docs]
- [ y ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ y ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [ y  ] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/342
- Issues :
https://github.com/openyurtio/openyurt/issues/358

My name is Lv jiawei.  I'm very interested in the cloud native technology and also be a member of Knative. My work focus on proprietary cloud project. There are some IOT sences in my project which maks me interested in edge computing. Openyurt has become one of the main exceeding potential opensource project which provides a solution of manage applications that run in the edge infrastructure. I'm very willing to contribute to the community.

**Comment by rambohe-ch** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@MIBc Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
