### ISSUE TITLE
[REQUEST Membership]: New membership for zc2638

### ISSUE THREAD

**Issue by zc2638** [openyurtio/community#22]
## GitHub Username

@zc2638

## Organization you are requesting membership in

@openyurtio

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pulls/zc2638
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree + 1

**Comment by rambohe-ch** [comment]
@zc2638 welcome you to apply for openyurt community member. Would you be able to have a simple introduction in the issue?

**Comment by zc2638** [comment]
Sorry, I don't know what to introduce.
@rambohe-ch

**Comment by rambohe-ch** [comment]
> Sorry, I don't know what to introduce.
> @rambohe-ch

Take easy, make a simple introduction is ok.  here is an example: https://github.com/openyurtio/community/issues/18

**Comment by Fei-Guo** [comment]
+1 welcome

**Comment by kadisi** [comment]
+1 welcome

**Comment by zc2638** [comment]
Hi, I'm working at @Daocloud.For cloud-native development, it is now mainly related to edge computing.
Thanks,
zc

**Comment by zzguang** [comment]
agree + 1

**Comment by Peeknut** [comment]
agree+1

**Comment by rambohe-ch** [comment]
> Hi, I'm working at @Daocloud.For cloud-native development, it is now mainly related to edge computing.
> Thanks,
> zc

@zc2638 Thank you for introduction.
Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
