### ISSUE TITLE
[REQUEST Membership]: New membership for vincent-pli

### ISSUE THREAD

**Issue by vincent-pli** [openyurtio/community#23]
## GitHub Username

@vincent-pli
## Organization you are requesting membership in

@openyurtio

## Sponsors

@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pulls?q=is%3Apr+author%3Avincent-pli+is%3Aclosed
- Issues :
https://github.com/openyurtio/openyurt/issues?q=is%3Aissue+author%3Avincent-pli+is%3Aclosed
https://github.com/openyurtio/openyurt/issues/created_by/vincent-pli

**Comment by rambohe-ch** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@vincent-pli Would you like to make a brief introduction?

**Comment by Fei-Guo** [comment]
+1

**Comment by vincent-pli** [comment]
Sure, I work for IBM and start working on opensource more than 2 years.
I have contributed to several opensource projects, like `tekton`, `kubeflow`, `knative` .etc.
Recently I focus on `multiple cluster` and `multiple tenant` fields, and watching on some interesting project like `karmada`, `virtual cluster`, `kcp` .etc.

Glad to join the `openyurt`

**Comment by gnunu** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@vincent-pli Thank you for introduction.
Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
