### ISSUE TITLE
[REQUEST Membership]: New membership for DrmagicE

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/community#24]
## GitHub Username
@DrmagicE

## Organization you are requesting membership in
@openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ]  I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/381
https://github.com/openyurtio/openyurt/pull/222
https://github.com/openyurtio/openyurt/pull/218
https://github.com/openyurtio/openyurt/pull/205
- Issues :
https://github.com/openyurtio/openyurt/issues/450
https://github.com/openyurtio/openyurt/issues/376

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
@DrmagicE Would you like to make a brief introduction to OpenYurt community?

**Comment by SataQiu** [comment]
+1 Welcome!

**Comment by DrmagicE** [comment]
> @DrmagicE Would you like to make a brief introduction to OpenYurt community?

Sure, I work for China Telecom and focus on CDN, Kubernetes and edge computing area. Glad to join the Openyurt Community and become a member!

**Comment by rambohe-ch** [comment]
> > @DrmagicE Would you like to make a brief introduction to OpenYurt community?
> 
> Sure, I work for China Telecom and focus on CDN, Kubernetes and edge computing area. Glad to join the Openyurt Community and become a member!

@DrmagicE Thank you for introduction.
Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
