### ISSUE TITLE
[REQUEST Membership]: New membership for adamzhoul

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/community#25]
## GitHub Username

@adamzhoul

## Organization you are requesting membership in

@openyurtio

## Sponsors

@rambohe-ch 

## Requirements

- [x]  I have joined in the community [Dingding]
- [ ]  I often attend Openyurt Community Week
- [x]  I have reviewed the [community membership docs]
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x]  I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x]  I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions

- pr: PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pulls?q=is%3Apr+author%3Aadamzhoul
- issue:
https://github.com/openyurtio/openyurt/issues?q=is%3Aissue+author%3Aadamzhoul+

## Brief Introduction

  focus on cloud-native development,  several years develop around k8s PaaS ServiceMesh, etc.
  k8s contributor,  
  working on edge-computing now.

**Comment by rambohe-ch** [comment]
agree +1

**Comment by DrmagicE** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@adamzhoul Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by adamzhoul** [comment]
thanks @rambohe-ch 

But where can I receive the message, GitHub notification?

**Comment by rambohe-ch** [comment]
> thanks @rambohe-ch
> 
> But where can I receive the message, GitHub notification?

@adamzhoul Yeah, you can check the github notification. and i have sent invitation and status is pending.

![image](https://user-images.githubusercontent.com/57081505/132854013-d52f0fa0-2170-4b86-8ffd-46623676cad4.png)

**Comment by adamzhoul** [comment]
> > thanks @rambohe-ch
> > But where can I receive the message, GitHub notification?
> 
> @adamzhoul Yeah, you can check the github notification. and i have sent invitation and status is pending.
> 
> ![image](https://user-images.githubusercontent.com/57081505/132854013-d52f0fa0-2170-4b86-8ffd-46623676cad4.png)

hi @rambohe-ch  

 I didn't receive any GitHub notification about this yet,  can u help check the status?

**Comment by rambohe-ch** [comment]
> 
> hi @rambohe-ch
> 
> I didn't receive any GitHub notification about this yet, can u help check the status?

you can check the notification or email.
![image](https://user-images.githubusercontent.com/57081505/133777872-c02252f5-ab7d-4738-969d-9d66283e790b.png)

**Comment by adamzhoul** [comment]
Hi @rambohe-ch 
I am sure notification received nothing 
sadly my email account meets some problems,  can't log in for some time.

 time to fix it now. 🤦‍♂️ 

Besides:  I change my Github primary email recently, can u help trigger again?

**Comment by adamzhoul** [comment]
Hi @rambohe-ch 

email problem fixed, 
found an email, but unfortunately, the invitation has expired. over 7 days.

do u mind resend one? 
thanks

**Comment by rambohe-ch** [comment]
> Hi @rambohe-ch
> 
> email problem fixed,
> found an email, but unfortunately, the invitation has expired. over 7 days.
> 
> do u mind resend one?
> thanks

@adamzhoul Thanks for your feedback. we have resent invitation, please have a check. and after joining member of OpenYurt, you need to check two points in this issue #14
