### ISSUE TITLE
[REQUEST Membership]: New membership for <YRXING>

### ISSUE THREAD

**Issue by YRXING** [openyurtio/community#26]
## GitHub Username
@YRXING

## Organization you are requesting membership in

@openyurtio

## Sponsors
@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/470
- Issues :

**Comment by rambohe-ch** [comment]
@YRXING I'm glad to support to apply OpenYurt community member. and would you like to make a brief introduction?

**Comment by rambohe-ch** [comment]
agree +1

**Comment by YRXING** [comment]
> @YRXING I'm glad to support to apply OpenYurt community member. and would you like to make a brief introduction?

I am  studying edge computing now and interested in cloud native technology like k8s, KubeEdge of which I have read some source code and did some development base on them. I now want to make some contribution to openyurt.

**Comment by qclc** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@YRXING Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
