### ISSUE TITLE
[REQUEST Membership]: New membership for <your github name>

### ISSUE THREAD

**Issue by ke-jobs** [openyurtio/community#28]
## GitHub Username
@ke-jobs

## Organization you are requesting membership in

@openyurtio

## Sponsors

@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [ ] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/475
- Issues :
https://github.com/openyurtio/openyurt/issues/410

## Brief Introduction
My name is ke-jobs. I'm very interested in the cloud native and edge compute technology. I will participate in the development of Openyurt in my spare time as an individual, hoping that the community can get better and better

**Comment by rambohe-ch** [comment]
@ke-jobs 
agree +1

btw: would you be able to replace `<your github name>` with `ke-jobs` in the title.
