### ISSUE TITLE
[REQUEST Membership]: New membership for Congrool

### ISSUE THREAD

**Issue by Congrool** [openyurtio/community#30]
## GitHub Username

@Congrool

## Organization you are requesting membership in

@openyurtio

## Sponsors

@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
openyurtio/openyurt#496
openyurtio/openyurt#512
openyurtio/openyurt#517
openyurtio/openyurt#520

- Issues:
openyurtio/openyurt#484
openyurtio/openyurt#511

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hello, I'm a student of ZJU SEL and major in Edge Computing. It's my honor to apply for the membership of OpenYurt Community. I'd like make my contribution to the development of the community.

**Comment by SataQiu** [comment]
+1

**Comment by denkensk** [comment]
agree +1
