### ISSUE TITLE
[REQUEST Membership]: New membership for luc99hen

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/community#32]
## GitHub Username

[@luc99hen](https://github.com/luc99hen)

## Organization you are requesting membership in

[openyurtio](https://github.com/openyurtio)

## Sponsors

[@rambohe-ch](https://github.com/rambohe-ch)

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
[fix bugs with lab apps and some additional improvements - yurt-dashboard](https://github.com/openyurtio/yurt-dashboard/pull/12)
[Docs: add user help doc - yurt-dashboard](https://github.com/openyurtio/yurt-dashboard/pull/15)

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, everyone. I am a postgraduate majored in Software Engineering in Tongji University. I am glad to get the chance to contribute to the OpenYurt. Currently, I was mainly engaged in [yurt-dashboard](https://github.com/openyurtio/yurt-dashboard) project. I'd like make more contributions to the development of the community.

**Comment by rambohe-ch** [comment]
@luc99hen welcome you to apply OpenYurt community member. agree +1

**Comment by windydayc** [comment]
agree +1

**Comment by qclc** [comment]
agree + 1

**Comment by Peeknut** [comment]
agree + 1

**Comment by rambohe-ch** [comment]
@luc99hen Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
