### ISSUE TITLE
[REQUEST Membership]: New membership for hhstu

### ISSUE THREAD

**Issue by hhstu** [openyurtio/community#33]
## GitHub Username
@hhstu

## Organization you are requesting membership in

openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
   https://github.com/openyurtio/openyurt/pull/727
   https://github.com/openyurtio/openyurt/pull/689
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, everyone. I am a develop of k8s working in the field of transportation. I am glad to get the chance to contribute to the OpenYurt. I'd like make more contributions to the development of the community.

**Comment by rambohe-ch** [comment]
@hhstu welcome you to apply member of OpenYurt community. agree +1

**Comment by Congrool** [comment]
Welcome. agree +1

**Comment by gnunu** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@hhstu Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14
