### ISSUE TITLE
[REQUEST Membership]: New membership for JcJinChen

### ISSUE THREAD

**Issue by JcJinChen** [openyurtio/community#34]
## GitHub Username
@JcJinChen

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/606
https://github.com/openyurtio/openyurt/pull/621

- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, everyone.I am a graduate student from Zhejiang University. I've been working on edge lightweight , including integrating OpenYurt with WasmEdge. I am glad to have a chance to take part in the OpenYurt Project. I'd like to make more contributions to the development of the community.

**Comment by rambohe-ch** [comment]
@JcJinChen welcome you to apply OpenYurt community member. agree +1

**Comment by kadisi** [comment]
agree +1

**Comment by zzguang** [comment]
agree +1

**Comment by Congrool** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@JcJinChen Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14

**Comment by hhstu** [comment]
agree +1
