### ISSUE TITLE
[REQUEST Membership]: New membership for huiwq1990

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/community#35]
## GitHub Username

@huiwq1990
## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [ ] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/792
https://github.com/openyurtio/openyurt/pull/751
https://github.com/openyurtio/openyurt/pull/741
https://github.com/openyurtio/openyurt/pull/750
https://github.com/openyurtio/yurt-dashboard/pull/29
https://github.com/openyurtio/yurt-edgex-manager/pull/11

- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction

Hello, I am a cloud-native developer for three years, and now focus on edge computing. I want use `openyurt` to support my bussiness, and  contribute it according actual demand.

**Comment by rambohe-ch** [comment]
@huiwq1990 welcome you to apply OpenYurt community member. agree +1

**Comment by gnunu** [comment]
agree +1

**Comment by qclc** [comment]
agree +1

**Comment by zzguang** [comment]
agree +1

**Comment by JcJinChen** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@huiwq1990 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
