### ISSUE TITLE
[REQUEST Membership]: New membership for zhaodiaoer

### ISSUE THREAD

**Issue by zhaodiaoer** [openyurtio/community#38]
## GitHub Username
@zhaodiaoer

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [X] I have joined in the community [Dingding] and [WeChat]
- [X] I often attend Openyurt Community Week
- [X] I have reviewed the [community membership docs]
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [X] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/832
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hello everyone, my name is zhaodiaoer, I am currently working on k8s & container releated work, I hope to become a member of openyurt community, thanks.

**Comment by rambohe-ch** [comment]
@zhaodiaoer Welcome you to apply OpenYurt community member. agree +1

**Comment by luckymrwang** [comment]
agree +1

**Comment by donychen1134** [comment]
agree +1

**Comment by qclc** [comment]
agree+1

**Comment by gnunu** [comment]
agree+1

**Comment by huiwq1990** [comment]
agree+1

**Comment by rambohe-ch** [comment]
@zhaodiaoer Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14

**Comment by zhaodiaoer** [comment]
@rambohe-ch  I have completed these tasks, thank you all guys :D
