### ISSUE TITLE
[REQUEST Membership]: New membership for lonelyCZ

### ISSUE THREAD

**Issue by lonelyCZ** [openyurtio/community#39]
## GitHub Username

@lonelyCZ

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/841
https://github.com/openyurtio/openyurt/pull/826
https://github.com/openyurtio/openyurt/pull/819
https://github.com/openyurtio/openyurt/pull/487

- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction

Hello everyone, my name is chengzhe, I am currently working on k8s & container releated work, I hope to become a member of openyurt community, thanks.

**Comment by rambohe-ch** [comment]
@lonelyCZ Welcome you to apply OpenYurt community member. agree +1

**Comment by Congrool** [comment]
Welcome. agree +1

**Comment by zzguang** [comment]
agree +1
@lonelyCZ  welcome!

**Comment by gnunu** [comment]
agree+1

**Comment by donychen1134** [comment]
Welcome. agree +1

**Comment by hhstu** [comment]
agree+1

**Comment by luc99hen** [comment]
agree+1

**Comment by rambohe-ch** [comment]
@lonelyCZ Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
