### ISSUE TITLE
[REQUEST Membership]: New membership for njucjc

### ISSUE THREAD

**Issue by njucjc** [openyurtio/community#43]
## GitHub Username

@njucjc 

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/raven/pull/43
https://github.com/openyurtio/raven/pull/32
https://github.com/openyurtio/raven/pull/27
https://github.com/openyurtio/raven/pull/18
https://github.com/openyurtio/raven/pull/9
https://github.com/openyurtio/raven-controller-manager/pull/16
https://github.com/openyurtio/raven-controller-manager/pull/6
https://github.com/openyurtio/openyurt.io/pull/111

- Issues :
https://github.com/openyurtio/raven/issues/31

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction

Hello everyone, my name is njucjc, I am currently working on k8s & container releated work, I hope to become a member of openyurt community, thanks.

**Comment by luckymrwang** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@njucjc welcome you to apply OpenYurt community member. agree +1

**Comment by rambohe-ch** [comment]
@njucjc Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14

**Comment by Congrool** [comment]
agree +1

**Comment by JcJinChen** [comment]
agree +1

**Comment by hhstu** [comment]
agree +1

**Comment by donychen1134** [comment]
agree +1

**Comment by DrmagicE** [comment]
agree +1
