### ISSUE TITLE
[REQUEST Membership]: New membership for arhell

### ISSUE THREAD

**Issue by Arhell** [openyurtio/community#47]
## GitHub Username
@arhell

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch

## Requirements

- [ ] I have joined in the community [Dingding] and [WeChat]
- [ ] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt.io/commits?author=Arhell
https://github.com/openyurtio/openyurt.io/pull/120
- Issues :

https://github.com/openyurtio/openyurt.io/issues/created_by/Arhell
https://github.com/openyurtio/openyurt.io/issues?q=is%3Aissue+author%3AArhell+is%3Aclosed

## Brief Introduction
I mainly work on the frontend, I want to work on the site, update it, fix bugs and more

**Comment by rambohe-ch** [comment]
@Arhell welcome you to apply OpenYurt community member. agree +1

**Comment by gnunu** [comment]
agree +1

**Comment by luc99hen** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@Arhell Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
