### ISSUE TITLE
[REQUEST Membership]: New membership for hxcGit

### ISSUE THREAD

**Issue by hxcGit** [openyurtio/community#48]
## GitHub Username
@hxcGit

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/yurt-dashboard/pull/25
https://github.com/openyurtio/openyurt.io/pull/70
https://github.com/openyurtio/openyurt.io/pull/79
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, everyone, my name is Hou Xuecheng. I am a student of East China Normal University, and I would like to join the openyurt community. I want to be able to continuously contribute to openyurt community.

**Comment by rambohe-ch** [comment]
@hxcGit Welcome you to apply, agree +1

**Comment by zzguang** [comment]
agree +1

**Comment by Congrool** [comment]
agree +1

**Comment by luc99hen** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@hxcGit Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
