### ISSUE TITLE
[REQUEST Membership]: New membership for lorrielau

### ISSUE THREAD

**Issue by lorrielau** [openyurtio/community#49]
## GitHub Username
@lorrielau

## Organization you are requesting membership in
openyurtio

## Sponsors
@rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt.io/pull/100
https://github.com/openyurtio/openyurt.io/pull/98
https://github.com/openyurtio/openyurt/pull/658

- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, everyone. I am a student from Zhejiang University and I'd like to join the community. Glad to be here, hope to work with you guys.

**Comment by Congrool** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@lorrielau welcome you to apply OpenYurt community member. agree +1

**Comment by rambohe-ch** [comment]
@lorrielau Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
