### ISSUE TITLE
[REQUEST Membership]: New membership for <pengbinbin1>

### ISSUE THREAD

**Issue by pengbinbin1** [openyurtio/community#52]
## GitHub Username

@pengbinbin1
## Organization you are requesting membership in

openyurtio

## Sponsors

@luckymrwang

## Requirements

- [ ] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
- https://github.com/openyurtio/openyurt/pull/814
- https://github.com/openyurtio/openyurt/pull/649
- https://github.com/openyurtio/openyurt/pull/632
- https://github.com/openyurtio/openyurt/pull/614
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by luckymrwang** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@pengbinbin1 welcome you to apply OpenYurt community member. agree +1

**Comment by Congrool** [comment]
agree+1

**Comment by zzguang** [comment]
agree +1

**Comment by donychen1134** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@pengbinbin1 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
