### ISSUE TITLE
[REQUEST Membership]: New membership for Lavender-QAQ

### ISSUE THREAD

**Issue by Lavender-QAQ** [openyurtio/community#53]
## GitHub Username

[Lavender-QAQ](https://github.com/Lavender-QAQ)

## Organization you are requesting membership in

openyurtio

## Sponsors

@lwmqwer 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/yurt-edgex-manager/pull/47
- Issues :
https://github.com/openyurtio/yurt-edgex-manager/issues/21

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hello, everyone. I am a postgraduate from Tongji University majoring in computer science. I'm currently interning at vmware. Currently, I was mainly engaged in [yurt-edgex-manager](https://github.com/openyurtio/yurt-edgex-manager) project. I'd like make more contributions to the development of the community.

**Comment by rambohe-ch** [comment]
@Lavender-QAQ welcome, agree +1

**Comment by Congrool** [comment]
welcome, agree +1

**Comment by zzguang** [comment]
welcome, agree +1

**Comment by rambohe-ch** [comment]
@Lavender-QAQ Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
