### ISSUE TITLE
[REQUEST Membership]: New membership for <LaurenceLiZhixin>

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [openyurtio/community#57]
## GitHub Username

@LaurenceLiZhixin

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch @Congrool 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/1148
https://github.com/openyurtio/openyurt/pull/1145
https://github.com/openyurtio/openyurt/pull/1144
https://github.com/openyurtio/openyurt/pull/1141
https://github.com/openyurtio/openyurt/pull/1130
https://github.com/openyurtio/openyurt/pull/1128
https://github.com/openyurtio/openyurt/pull/1126
https://github.com/openyurtio/openyurt/pull/1125
https://github.com/openyurtio/openyurt/pull/1123
https://github.com/openyurtio/openyurt/pull/1121
https://github.com/openyurtio/openyurt/pull/1120
https://github.com/openyurtio/openyurt/pull/1119
https://github.com/openyurtio/openyurt/pull/1117

- Issues :
https://github.com/openyurtio/openyurt/issues/1129
https://github.com/openyurtio/openyurt/issues/1101

## Brief Introduction
Hi guys,I am Laurence, 23 years old, Apache Dubbo [PMC](https://www.apache.org/dev/pmc.html), author of [alibaba/IOC-golang](https://github.com/alibaba/ioc-golang.git) . A cloud native engineer from Hangzhou, China, graduated from [SYSU](http://www.sysu.edu.cn/cn/index.htm), software engineering bachelor’s degree. I Mainly research microservices, cloud-native, IOC framework, Golang, Edge Computing. Contributor of apache/dubbo, apache/rocketmq, dapr, cloudwego/kitex and so on.

Currently, I am working on the development of edge application platform in the cloud native team, responsible for practicing the application of Openyurt in large-scale edge cluster scenarios. And I hope to make more contributions to the community after becoming A member, Thanks.

**Comment by Congrool** [comment]
Welcome! agree +1

**Comment by rambohe-ch** [comment]
@LaurenceLiZhixin Thank you for your contributions to OpenYurt, and welcome you to apply OpenYurt community member. agree +1

**Comment by YTGhost** [comment]
agree +1

**Comment by LavenderQAQ** [comment]
agree +1

**Comment by luc99hen** [comment]
agree +1

**Comment by donychen1134** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@LaurenceLiZhixin Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14

**Comment by LaurenceLiZhixin** [comment]
Thanks. I found Qr code of openyurt community dingtalk group is expired. By the way, do we have wechat community group? 
@rambohe-ch

**Comment by rambohe-ch** [comment]
> Thanks. I found Qr code of openyurt community dingtalk group is expired. By the way, do we have wechat community group? @rambohe-ch

@LaurenceLiZhixin I have updated the QR code in issue #14
