### ISSUE TITLE
[REQUEST Membership]: New membership for yanyhui

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/community#6]
## GitHub Username

yanyhui
## Organization you are requesting membership in

openyurtio

## Sponsors

rambohe-ch
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/268
https://github.com/openyurtio/openyurt/pull/275
https://github.com/openyurtio/yurt-app-manager/pull/16
https://github.com/openyurtio/openyurt/pull/299
- Issues :
https://github.com/openyurtio/openyurt/issues/262
https://github.com/openyurtio/openyurt/issues/274
openyurtio/openyurt#286
https://github.com/openyurtio/openyurt/issues/298
[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by kadisi** [comment]
+1

**Comment by rambohe-ch** [comment]
@yanyhui congratulations you to become member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message and keep the member public.
