### ISSUE TITLE
[REQUEST Membership]: New membership for <Rui-Gan>

### ISSUE THREAD

**Issue by Rui-Gan** [openyurtio/community#62]
## GitHub Username

@Rui-Gan

## Organization you are requesting membership in

openyurtio

## Sponsors

@wawlian @rambohe-ch 

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/yurt-edgex-manager/pull/48
https://github.com/openyurtio/yurt-edgex-manager/pull/50
https://github.com/openyurtio/yurt-edgex-manager/pull/51
https://github.com/openyurtio/yurt-edgex-manager/pull/53
https://github.com/openyurtio/yurt-edgex-manager/pull/70
https://github.com/openyurtio/yurt-edgex-manager/pull/75
https://github.com/openyurtio/yurt-edgex-manager/pull/80
https://github.com/openyurtio/yurt-edgex-manager/pull/81
https://github.com/openyurtio/yurt-edgex-manager/pull/83

- Issues :
https://github.com/openyurtio/yurt-edgex-manager/issues/22
https://github.com/openyurtio/yurt-edgex-manager/issues/34
https://github.com/openyurtio/yurt-edgex-manager/issues/49
https://github.com/openyurtio/yurt-edgex-manager/issues/62
https://github.com/openyurtio/yurt-edgex-manager/issues/66
https://github.com/openyurtio/yurt-edgex-manager/issues/67

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hi, I am a graduate student majoring in software engineering at Zhejiang University. I am very interested in k8s & container, and I'd like to make more contributions to the community.

**Comment by LavenderQAQ** [comment]
Welcome! agree +1

**Comment by rambohe-ch** [comment]
@Rui-Gan welcome you to apply OpenYurt community member, agree +1

**Comment by wawlian** [comment]
@Rui-Gan Welcome！agree +1

**Comment by fengshunli** [comment]
Welcome！agree +1

**Comment by YTGhost** [comment]
Welcome！agree +1

**Comment by zzguang** [comment]
Welcome! agree + 1

**Comment by luckymrwang** [comment]
Welcome! agree + 1

**Comment by rambohe-ch** [comment]
@Rui-Gan Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
