### ISSUE TITLE
[REQUEST Membership]: New membership for qclc

### ISSUE THREAD

**Issue by qclc** [openyurtio/community#7]
## GitHub Username

qclc

## Organization you are requesting membership in

openyurtio

## Sponsors

rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/231
https://github.com/openyurtio/openyurt/pull/225
https://github.com/openyurtio/openyurt/issues/325

- Issues :
https://github.com/openyurtio/openyurt/issues/325
https://github.com/openyurtio/openyurt/issues/281
[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
agree +1

**Comment by kadisi** [comment]
agree +1
