### ISSUE TITLE
[REQUEST Membership]: New membership for <y-ykcir>

### ISSUE THREAD

**Issue by y-ykcir** [openyurtio/community#70]
## GitHub Username

@y-ykcir
## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch 
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
openyurtio/openyurt#1268
openyurtio/openyurt#1355
openyurtio/openyurt#1367
openyurtio/openyurt#1398
openyurtio/openyurt#1404
- Issues :
openyurtio/openyurt#1361

## Brief Introduction
Hello, I am a student from  Zhejiang University. I am very interested in openyurt, and I'd like to make more contributions to the development of the community.

**Comment by Congrool** [comment]
agree +1, welcome!

**Comment by rambohe-ch** [comment]
@y-ykcir welcome you to apply OpenYurt community member, agree +1

**Comment by YTGhost** [comment]
agree +1, welcome!

**Comment by BSWANG** [comment]
agree +1, welcome!

**Comment by luckymrwang** [comment]
agree +1, welcome!

**Comment by Ophira0110** [comment]
agree +1, welcome!

**Comment by rambohe-ch** [comment]
@y-ykcir Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
