### ISSUE TITLE
[REQUEST Membership]: New membership for <huweihuang>

### ISSUE THREAD

**Issue by huweihuang** [openyurtio/community#71]
## GitHub Username

@huweihuang

## Organization you are requesting membership in

openyurtio

## Sponsors

@rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:

   - https://github.com/openyurtio/openyurt/pull/1366
   - https://github.com/openyurtio/openyurt/pull/1114
   - https://github.com/openyurtio/apiserver-network-proxy/pull/1
   - https://github.com/openyurtio/openyurt-helm/pull/9

- Issues :
   https://github.com/openyurtio/openyurt/issues/1440

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction

I'm a developer who is very interested in the community. I have years of practical experience in k8s and containers, I am currently using openyurt in the scene of edge containers. And I'd like to make more contributions to the community.

**Comment by rambohe-ch** [comment]
@huweihuang welcome you to apply OpenYurt community member. agree +1

**Comment by Rui-Gan** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@huweihuang Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
