### ISSUE TITLE
[REQUEST Membership]: New membership for <wangxye>

### ISSUE THREAD

**Issue by wangxye** [openyurtio/community#74]
## GitHub Username

@wangxye
## Organization you are requesting membership in

openyurtio

## Sponsors

@gnunu
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openyurtio/openyurt/pull/1666
https://github.com/openyurtio/openyurt/pull/1647
https://github.com/openyurtio/openyurt/pull/1607
https://github.com/openyurtio/yurt-edgex-manager/pull/102
- Issues :
https://github.com/openyurtio/openyurt/issues/1626
https://github.com/openyurtio/openyurt/issues/1615
https://github.com/openyurtio/openyurt/issues/1580
https://github.com/openyurtio/yurt-edgex-manager/issues/101

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
Hello everyone, I am a graduate student from Zhejiang University majoring in software engineering with a keen interest in cloud-native technologies.  Specifically, I am passionate about both K8s and Docker, and I'd like to contribute more to the development of the community.

**Comment by LavenderQAQ** [comment]
agree +1

**Comment by gnunu** [comment]
agree

**Comment by rambohe-ch** [comment]
@wangxye welcome, agree+1

**Comment by rambohe-ch** [comment]
@wangxye Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14
