### ISSUE TITLE
[REQUEST Membership]: New membership for <lilongfeng0902>

### ISSUE THREAD

**Issue by lilongfeng0902** [openyurtio/community#77]
## GitHub Username

@lilongfeng0902
## Organization you are requesting membership in

openyurtio

## Sponsors

@luckymrwang
## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:
- https://github.com/openyurtio/openyurt/pull/1826
- https://github.com/openyurtio/openyurt/pull/1825
- https://github.com/openyurtio/openyurt/pull/1814
- https://github.com/openyurtio/openyurt/pull/1698
- https://github.com/openyurtio/openyurt/pull/1405
- https://github.com/openyurtio/openyurt/pull/1401
- Issues :

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

## Brief Introduction
I like open source projects and hope to contribute to the community with like-minded people.

**Comment by luckymrwang** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@lilongfeng0902 welcome, agree +1

**Comment by YTGhost** [comment]
agree +1

**Comment by LavenderQAQ** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@lilongfeng0902 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue https://github.com/openyurtio/community/issues/14

**Comment by lilongfeng0902** [comment]
> @lilongfeng0902 Congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

Thanks for your inviting, I have checked two points in this issue #14
