### ISSUE TITLE
[REQUEST Membership]: New membership for duanjia85

### ISSUE THREAD

**Issue by duanjia85** [openyurtio/community#8]
## Organization you are requesting membership in

openyurtio

## Sponsors
rambohe-ch
kadisi

## Requirements

- [ ] I have joined in the community [Dingding] and [WeChat]
- [ ] I often attend Openyurt Community Week
- [ ] I have reviewed the [community membership docs]
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [ ] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:

- Issues :

**Comment by kadisi** [comment]
agree +1

**Comment by rambohe-ch** [comment]
agree +1
