### ISSUE TITLE
[REQUEST Membership]: New membership for mauricewei

### ISSUE THREAD

**Issue by mauricewei** [openyurtio/community#9]
## GitHub Username

mauricewei

## Organization you are requesting membership in

openyurtio

## Sponsors

kadisi
rambohe-ch

## Requirements

- [x] I have joined in the community [Dingding] and [WeChat]
- [x] I often attend Openyurt Community Week
- [x] I have reviewed the [community membership docs]
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenYurt subprojects

## List of your contributions 
- PRs reviewed / authored:

- Issues:
https://github.com/openyurtio/openyurt/pull/349
https://github.com/openyurtio/openyurt/issues/356
https://github.com/openyurtio/openyurt/issues/355

[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by rambohe-ch** [comment]
@mauricewei Thank you for requesting member of OpenYurt.
Would you please to submit some issues or pull request at first. and you can check the member requirements here: https://github.com/openyurtio/community/blob/main/community-membership.md#requirements

we will wait for you to update this issue after any contributions to OpenYurt.

**Comment by kadisi** [comment]
agree

**Comment by rambohe-ch** [comment]
agree +1

**Comment by rambohe-ch** [comment]
@mauricewei Would you like to introduce yourself to the community ？
and congratulations you to become a member of OpenYurt community. We have sent a github message to invite you as member of OpenYurt, please check the message. and after joining member of OpenYurt, you need to check two points in this issue #14

**Comment by mauricewei** [comment]
My name is Wei Meng. I work in China Unicom. I'm engaged in k8s and openstack project development. I'm good at Python golang programming. I'm very interested in the open source community and very happy to join openyurt community
